name: CMake on multiple platforms

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      # Explicitly defining the matrix combinations ensures we get Linux/macOS cross x86/ARM
      matrix:
        include:
          # --- Linux (Ubuntu) ---
          - os: ubuntu-latest
            arch: x86_64
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            arch: x86_64
            c_compiler: clang
            cpp_compiler: clang++
          - os: ubuntu-24.04-arm
            arch: arm64
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-24.04-arm
            arch: arm64
            c_compiler: clang
            cpp_compiler: clang++

          # --- macOS ---
          - os: macos-15-intel  # Intel x86_64 runner
            arch: x86_64
            c_compiler: clang
            cpp_compiler: clang++
          - os: macos-latest  # Apple Silicon M1/M2/M3 ARM64 runner
            arch: arm64
            c_compiler: clang
            cpp_compiler: clang++

    steps:
    - uses: actions/checkout@v4

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=Release
        -DSIPM_ENABLE_TEST=ON
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config Release
