name: Build and upload to TestPyPI
on:
    push:
        branches:
            - main
            - dev
    release:
        types:
            - published
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build_sdist:
        name: Build SDist
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Build SDist
              run: pipx run build --sdist
            - name: Check metadata
              run: pipx run twine check dist/*
            - uses: actions/upload-artifact@v4
              with:
                  name: cibw-sdist
                  path: dist/*.tar.gz

    build_wheels:
        name: Wheels on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-latest
                    - macos-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pypa/cibuildwheel@v2.17
              env:
                  CIBW_SKIP: "*-manylinux_i686"
                  CIBW_BUILD: cp3*
                  CIBW_BEFORE_BUILD: pip install -U pip && pip install pybind11
                  CIBW_ARCHS_MACOS: x86_64 universal2
            - name: Upload wheels
              uses: actions/upload-artifact@v4
              with:
                  name: cibw-wheels-${{ matrix.os }}
                  path: wheelhouse/*.whll

    upload_test_pypi:
        name: Publish package distributions to TestPyPI
        needs:
            - build_wheels
            - build_sdist
        runs-on: ubuntu-latest
        environment: testpypi
        if: github.event_name == 'push'
        steps:
            - uses: actions/setup-python@v5
              with:
                  python-version: 3.x
            - uses: actions/download-artifact@v4
              with:
                  pattern: cibw-*
                  path: dist
                  merge-multiple: true
            - uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  repository-url: https://test.pypi.org/legacy/
