name: Build and upload to TestPyPI

on:
  push:
    branches: [main, dev]

  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]


    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: 3.9

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_SKIP: "*-manylinux_i686"
          CIBW_BUILD: cp3* pp3*
          CIBW_BEFORE_BUILD: pip install -U pip && pip install pybind11
          CIBW_ARCHS_MACOS: x86_64 universal2

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution on ${{ matrix.os }}

    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: 3.9

      - name: Install Pybind11
        run: python -m pip install -U pip && python -m pip install pybind11

      - name: Build sdist
        run: python setup.py sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz
