name: Build and upload to TestPyPI
on:
    push:
        branches:
            - main
            - dev
    release:
        types:
            - published
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    build_sdist:
        name: Building Source Distribution
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Running sdist build with pipx
              run: pipx run build --sdist

            - uses: actions/upload-artifact@v4
              with:
                  name: cibw-sdist
                  path: dist/*.tar.gz

    build_wheels:
        name: Building Wheels on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-latest
                    - macos-13
                    - macos-14
        steps:
            - uses: actions/checkout@v4
            - name: Build Wheel
              run: pipx run cibuildwheel==2.21.1
              env:
                  CIBW_SKIP: "*i686"
                  CIBW_BUILD: cp3*
                  CIBW_BEFORE_BUILD: pip install -U pip && pip install pybind11
                  CIBW_ARCHS_MACOS: auto64
                  CIBW_ARCHS_LINUX: auto64

            - name: Upload wheels
              uses: actions/upload-artifact@v4
              with:
                  name: cibw-wheels-${{ matrix.os }}
                  path: ./wheelhouse/*.whl

    upload_test_pypi:
        name: Publish package distributions to TestPyPI
        needs:
            - build_wheels
            - build_sdist
        runs-on: ubuntu-latest
        environment:
            name: testpypi
            url: https://test.pypi.org/p/SiPM
        permissions:
            id-token: write

        if: github.event_name == 'push'
        steps:
            - name: Download all the sdists
              uses: actions/download-artifact@v4
              with:
                  pattern: cibw-*
                  path: dist/
                  merge-multiple: true
            - name: Publish distribution to TestPyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  user: __token__
                  password: ${{ secrets.PYPI_API_TOKEN }}
                  repository-url: https://test.pypi.org/legacy/
