name: Build and upload to TestPyPI

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: 3.9

      - name: Build wheels
        uses: joerick/cibuildwheel@v1.11.0
        env:
          CIBW_SKIP: cp27-* pp* *-manylinux_i686
          CIBW_BUILD: cp3*
          CIBW_BEFORE_BUILD: pip install -U pip && pip install pybind11
          CIBW_ARCHS_MACOS: x86_64 universal2

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution on ${{ matrix.os }}

    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: 3.9

      - name: Install Pybind11
        run: python -m pip install -U pip && python -m pip install pybind11

      - name: Build sdist
        run: python setup.py sdist

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz
